"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ID' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations = {
  ID: {
    // Dashboard / Table
    'item_th': 'Barang',
    'spec_th': 'Spek',
    'price_th': 'Harga',
    'qty_th': 'Stok',
    'status_th': 'Status',
    'low_status': 'LOW',
    'ok_status': 'OK',
    'no_data': 'Data inventori tidak ditemukan',
    'import_prompt': 'Impor file Excel untuk mengisi dashboard Anda',
    'displaying_records': 'Menampilkan {start} - {end} dari {total} data',
    'prev': 'Sebelumnya',
    'next': 'Selanjutnya',
    'sign_out': 'Keluar',
    'logout_confirm': 'Apakah Anda yakin ingin keluar dari akun Anda?',
    'exit_now': 'Keluar Sekarang',
    'stay_here': 'Tetap di Sini',
    'misc': 'Lain-lain',
    
    // Price Check
    'price_check': 'Cek Harga',
    'price_check_desc': 'Scan barcode untuk cek harga barang',
    'camera': 'Kamera',
    'scan_placeholder': 'Ketik barcode atau scan...',
    'search_inventory': 'Cari inventori...',
    'import': 'Impor',
    'export': 'Ekspor',
    'import_success': 'Impor Berhasil',
    'import_failed': 'Impor Gagal',
    
    // Management Page
    'opname_results': 'Hasil Stok Opname',
    'search_placeholder': 'Cari apapun (barang, rak, nama, divisi)...',
    'all_users': 'Semua Pengguna',
    'all_divisions': 'Semua Divisi',
    'filter_by_user': 'Berdasarkan Personel',
    'filter_by_division': 'Berdasarkan Departemen',
    'export_data': 'Ekspor Data',
    'list_view': 'Tampilan Daftar',
    'stats_view': 'Tampilan Statistik',
    'items': 'Barang',
    'last_update': 'Update Terakhir',
    'actions': 'Aksi',
    'plus_minus': 'Plus/Minus',
    'total_items': 'Total Barang',
    'surplus_items': 'Barang Lebih',
    'shortage_items': 'Barang Kurang',
    'stock_value': 'Nilai Stok',
    'discrepancy_value': 'Nilai Selisih',
    'purchase_price_value': 'Nilai harga beli',
    'action_required': 'Tindakan Diperlukan',
    'below_threshold': 'Barang di bawah stok minimum',
    'progress': 'Progres',
    'verified_skus': 'SKU Terverifikasi',
    'discrepancy': 'Selisih',
    'team': 'Tim',
    'active_personnel': 'Personel Aktif',
    'access_denied': 'AKSES DITOLAK',
    'no_permission': 'Anda tidak memiliki izin yang diperlukan untuk mengakses Dashboard Manajemen Opname.',
    'return_to_home': 'Kembali ke Beranda',
    'workforce_response': 'Respon Tenaga Kerja',
    'warehouse_rack': 'Rak Gudang',
    'action_th': 'Aksi',
    'scanned_by': 'Discan oleh',
    'updated_at': 'Diperbarui',
    'no_matching_activity': 'Tidak ada aktivitas yang cocok dengan filter Anda.',
    'workforce_distribution': 'Distribusi Tenaga Kerja',
    'value_summary': 'Ringkasan Nilai',
    'total_stock_value': 'Total Nilai Stok',
    'total_diff_value': 'Total Nilai Plus/Minus',
    'delete_item_record': 'Hapus Data Barang',
    'delete_item_confirm': 'Apakah Anda yakin ingin menghapus {name} dari data rak ini?',
    'opname_qty_label': 'Qty Opname',
    'yes_proceed': 'Ya, Lanjutkan',
    'items_count_label': '{count} Barang',
    
    // Stock Opname Page
    'start_session': 'Mulai Sesi',
    'active_session': 'Sesi Aktif',
    'shelf_number': 'Nomor Rak / Lokasi',
    'shelf_number_placeholder': 'Contoh: RAK-A1',
    'inspector_name': 'Nama Pemeriksa (Checker)',
    'inspector_name_placeholder': 'Masukkan nama Anda',
    'division_dept': 'Divisi (Dept)',
    'division_dept_placeholder': 'Masukkan Divisi/Bagian',
    'start_scanning': 'Mulai Scanning',
    'session_setup': 'Setup Sesi',
    'initialize_session_msg': 'Inisialisasi sesi pengambilan stok Anda',
    'scan_barcode': 'Scan Barcode',
    'manual_search': 'Pencarian Manual',
    'save_close_session': 'Simpan & Tutup Sesi',
    'item_found': 'Barang Ditemukan',
    'item_not_found': 'Barang Tidak Ditemukan',
    'item_not_found_msg': 'Sistem tidak menemukan barang:',
    'enter_qty': 'Masukkan Jumlah',
    'cancel': 'Batal',
    'confirm': 'Konfirmasi',
    'edit_qty': 'Ubah Jumlah',
    'item_already_verified': 'Barang Sudah Diverifikasi',
    'duplicate_msg': 'telah diverifikasi di rak ini. Ingin ubah jumlah atau batal?',
    'delete_record': 'Hapus Data',
    'delete_record_confirm': 'Apakah Anda yakin ingin menghapus data verifikasi untuk "{name}"?',
    'save_failed': 'Simpan Gagal',
    'save_failed_msg': 'Tidak dapat mendaftarkan verifikasi. Cek koneksi Anda.',
    'export_failed': 'Ekspor Gagal',
    'no_records_to_export': 'Tidak ada data untuk diekspor.',
    'clear_history': 'Hapus Riwayat',
    'clear_history_confirm': 'Yakin ingin menghapus semua riwayat opname? Ini tidak bisa dibatalkan.',
    'loading_inventory': 'Memuat Inventori...',
    'set_0': 'Set 0',
    'reset': 'Reset',
    'system_label': 'Sistem:',
    'plus_minus_label': 'Plus/Minus:',
    'save_btn': 'SIMPAN',
    'session_log': 'Log Sesi',
    'items_count': '{count} Barang',
    'edit_label': 'Ubah',
    'delete_label': 'Hapus',
    'empty_log': 'Log kosong untuk rak ini',
    'start_scanning_prompt': 'Mulai scanning untuk menambah data',
    'force_reset': 'Paksa Reset Riwayat',
    'back_to_dashboard': 'Kembali ke Dashboard',
    'yes_delete': 'Ya, Hapus',
    
    // Export Headers
    'item': 'Barang',
    'item_code': 'Kode Barang',
    'barcode': 'Barcode',
    'unit': 'Satuan',
    'rack': 'Rak',
    'division': 'Divisi',
    'inspector': 'Pemeriksa',
    'physical': 'Fisik',
    'system': 'Sistem',
    'diff': 'Selisih',
    'price': 'Harga',
    'date': 'Tanggal',

    // Notifications
    'session_finished': 'Sesi Selesai',
    'live_update': 'Update Langsung',
    'new_entry': 'Data baru disimpan',
    'completed': 'menyelesaikan',
    'verified_on': 'verifikasi di',
    'close': 'Tutup',
    'manual_entry_label': 'Entri Manual / USB Scan',
    'scanner_tip': 'Sistem mendukung semua format barcode (EAN, UPC, Code 128, QR). Gunakan scanner USB atau tekan tombol **Kamera** untuk hasil instan.',
    'item_not_found_price': 'Barang dengan kode {code} tidak ditemukan.',
    'rack_overview': 'Ringkasan Rak',
    'verified_locations': 'Lokasi Terverifikasi',
    'location_id_verified': 'ID Lokasi Terverifikasi',
    'items_label': 'Barang',
    'preview_rack': 'Pratinjau Rak',
    'resume_rack': 'Lanjut Sesi Rak',
    'product_gallery_management': 'Galeri Produk & Manajemen',
    'search_products': 'Cari produk...',
    'edit_product': 'Ubah Produk',
    'no_image': 'Tidak ada Gambar',
    'upload_to_display': 'Unggah untuk menampilkan',
    'no_products_found': 'Produk tidak ditemukan',
    'adjust_search': 'Coba sesuaikan kata kunci pencarian Anda',
    'page_label': 'Halaman',
    'of_label': 'dari',
    'item_id': 'ID Barang',
    'product_image': 'Gambar Produk',
    'change_image': 'Ubah Gambar',
    'product_name': 'Nama Produk',
    'internal_code': 'Kode Internal',
    'sell_price': 'Harga Jual',
    'current_stock': 'Stok Saat Ini',
    'discard_changes': 'Batalkan Perubahan',
    'save_changes': 'Simpan Perubahan',
    'stock_level_healthy': 'Level stok aman',
    'manage_users': 'Kelola User',
    'accounts_permissions': 'Akun & Izin',
    'add_new_user': 'Tambah User Baru',
    'loading_accounts': 'Memuat Akun...',
    'created_at_label': 'Dibuat Pada',
    'no_users_found': 'User tidak ditemukan',
    'new_user_account': 'Akun User Baru',
    'full_name': 'Nama Lengkap',
    'email_address': 'Alamat Email',
    'password_label': 'Kata Sandi',
    'role_label': 'Peran',
    'standard_user': 'User Standar',
    'system_admin': 'Administrator Sistem',
    'update_account': 'PERBARUI AKUN',
    'create_account': 'BUAT AKUN',
    'confirm_delete': 'Konfirmasi Hapus',
    'reports': 'Laporan',
    'history_archive': 'Riwayat & Arsip',
    'manage_dashboard': 'Kelola Dashboard',
    'export_excel': 'Ekspor Excel',
    'filter_results': 'Filter hasil...',
    'item_info_th': 'Info Barang',
    'timestamp_th': 'Waktu',
    'diff_th': 'Selisih',
    'no_results_found': 'Hasil opname tidak ditemukan.',
    'showing_page': 'Menampilkan halaman {current} dari {total}',
    'yes_clear_all': 'Ya, Hapus Semua',
    'export_error': 'Ekspor Gagal',
    'clear_history_title': 'Hapus Semua Riwayat',
    'clear_history_msg': 'Apakah Anda yakin ingin menghapus semua data opname secara permanen? Tindakan ini tidak dapat dibatalkan.',
    'welcome_back': 'Selamat Datang Kembali',
    'enter_credentials': 'Masukkan kredensial Anda untuk mengelola inventori',
    'invalid_login': 'Email atau password salah',
    'unexpected_error': 'Terjadi kesalahan yang tidak terduga',
    'login_to_dashboard': 'Masuk ke Dashboard',
    'session_complete': 'Sesi Selesai'
  },
  EN: {
    // Dashboard / Table
    'item_th': 'Item',
    'spec_th': 'Spec',
    'price_th': 'Price',
    'qty_th': 'Qty',
    'status_th': 'Status',
    'low_status': 'LOW',
    'ok_status': 'OK',
    'no_data': 'No inventory data found',
    'import_prompt': 'Import an Excel file to populate your dashboard',
    'displaying_records': 'Displaying {start} - {end} of {total} records',
    'prev': 'Prev',
    'next': 'Next',
    'sign_out': 'Sign Out',
    'logout_confirm': 'Are you sure you want to log out of your account?',
    'exit_now': 'Exit Now',
    'stay_here': 'Stay Here',
    'misc': 'Misc',

    // Price Check
    'price_check': 'Price Check',
    'price_check_desc': 'Scan barcode to check item price',
    'camera': 'Camera',
    'scan_placeholder': 'Type barcode or scan...',
    'search_inventory': 'Search inventory...',
    'import': 'Import',
    'export': 'Export',
    'import_success': 'Import Success',
    'import_failed': 'Import Failed',

    // Management Page
    'opname_results': 'Stock Opname Results',
    'search_placeholder': 'Search anything (item, rack, name, division)...',
    'all_users': 'All Users',
    'all_divisions': 'All Divisions',
    'filter_by_user': 'By Personnel',
    'filter_by_division': 'By Department',
    'export_data': 'Export Data',
    'list_view': 'List View',
    'stats_view': 'Stats View',
    'items': 'Items',
    'last_update': 'Last Update',
    'actions': 'Actions',
    'plus_minus': 'Plus/Minus',
    'total_items': 'Total Items',
    'surplus_items': 'Surplus Items',
    'shortage_items': 'Shortage Items',
    'stock_value': 'Stock Value',
    'discrepancy_value': 'Discrepancy Value',
    'purchase_price_value': 'Purchase price value',
    'action_required': 'Action Required',
    'below_threshold': 'Items below min threshold',
    'progress': 'Progress',
    'verified_skus': 'Verified SKUs',
    'discrepancy': 'Discrepancy',
    'team': 'Team',
    'active_personnel': 'Active Personnel',
    'access_denied': 'ACCESS DENIED',
    'no_permission': 'You do not have the necessary permissions to access the Opname Management Dashboard.',
    'return_to_home': 'Return to Home',
    'workforce_response': 'Workforce Response',
    'warehouse_rack': 'Warehouse Rack',
    'action_th': 'Action',
    'scanned_by': 'Scanned by',
    'updated_at': 'Updated',
    'no_matching_activity': 'No activity matching your filters.',
    'workforce_distribution': 'Workforce Distribution',
    'value_summary': 'Value Summary',
    'total_stock_value': 'Total Stock Value',
    'total_diff_value': 'Total Plus/Minus Value',
    'delete_item_record': 'Delete Item Record',
    'delete_item_confirm': 'Are you sure you want to delete {name} from this rack record?',
    'opname_qty_label': 'Opname Qty',
    'yes_proceed': 'Yes, Proceed',
    'items_count_label': '{count} Items',

    // Stock Opname Page
    'shelf_number': 'Shelf Number / Location',
    'shelf_number_placeholder': 'e.g. RAK-A1',
    'inspector_name': 'Inspector Name (Checker)',
    'inspector_name_placeholder': 'Enter your name',
    'division_dept': 'Division (Dept)',
    'division_dept_placeholder': 'Enter Division/Dept',
    'start_scanning': 'Start Scanning',
    'session_setup': 'Session Setup',
    'initialize_session_msg': 'Initialize your stock-taking session',
    'start_session': 'Start Session',
    'active_session': 'Active Session',
    'rack_number': 'Rack Number',
    'operator_name': 'Operator Name',
    'scan_barcode': 'Scan Barcode',
    'manual_search': 'Manual Search',
    'save_close_session': 'Save & Close Session',
    'item_found': 'Item Found',
    'item_not_found': 'Item Not Found',
    'item_not_found_msg': 'System could not find item:',
    'enter_qty': 'Enter Quantity',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'edit_qty': 'Edit Quantity',
    'item_already_verified': 'Item Already Verified',
    'duplicate_msg': 'has already been verified. Would you like to edit quantity or cancel?',
    'delete_record': 'Delete Record',
    'delete_record_confirm': 'Are you sure you want to delete the verification record for "{name}"?',
    'save_failed': 'Save Failed',
    'save_failed_msg': 'Could not save verification. Please check your connection.',
    'export_failed': 'Export Failed',
    'no_records_to_export': 'There are no records to export.',
    'clear_history': 'Clear History',
    'clear_history_confirm': 'Are you sure you want to clear all opname history? This cannot be undone.',
    'loading_inventory': 'Loading Inventory...',
    'set_0': 'Set 0',
    'reset': 'Reset',
    'system_label': 'System:',
    'plus_minus_label': 'Plus/Minus:',
    'save_btn': 'SAVE',
    'session_log': 'Session Log',
    'items_count': '{count} Items',
    'edit_label': 'Edit',
    'delete_label': 'Delete',
    'empty_log': 'Empty log for this rack',
    'start_scanning_prompt': 'Start scanning to add records',
    'force_reset': 'Force Reset History',
    'back_to_dashboard': 'Back to Dashboard',
    'yes_delete': 'Yes, Delete',

    // Export Headers
    'item': 'Item',
    'item_code': 'Item Code',
    'barcode': 'Barcode',
    'unit': 'Unit',
    'rack': 'Rack',
    'division': 'Division',
    'inspector': 'Inspector',
    'physical': 'Physical',
    'system': 'System',
    'diff': 'Diff',
    'price': 'Price',
    'date': 'Date',

    // Notifications
    'session_finished': 'Session Finished',
    'live_update': 'Live Update',
    'new_entry': 'New entry saved',
    'completed': 'completed',
    'verified_on': 'verified on',
    'close': 'Close',
    'manual_entry_label': 'Manual Entry / USB Scan',
    'scanner_tip': 'System supports all barcode formats (EAN, UPC, Code 128, QR). Use USB scanner or press **Camera** button for instant results.',
    'item_not_found_price': 'Item with code {code} not found.',
    'rack_overview': 'Rack Overview',
    'verified_locations': 'Verified Locations',
    'location_id_verified': 'Location ID Verified',
    'items_label': 'Items',
    'preview_rack': 'Preview Rack',
    'resume_rack': 'Resume Rack Session',
    'product_gallery_management': 'Product Gallery & Management',
    'search_products': 'Search products...',
    'edit_product': 'Edit Product',
    'no_image': 'No Image',
    'upload_to_display': 'Upload to display',
    'no_products_found': 'No Products Found',
    'adjust_search': 'Try adjusting your search query',
    'page_label': 'Page',
    'of_label': 'of',
    'item_id': 'Item ID',
    'product_image': 'Product Image',
    'change_image': 'Change Image',
    'product_name': 'Product Name',
    'internal_code': 'Internal Code',
    'sell_price': 'Sell Price',
    'current_stock': 'Current Stock',
    'discard_changes': 'Discard Changes',
    'save_changes': 'Save Changes',
    'stock_level_healthy': 'Stock level healthy',
    'manage_users': 'Manage Users',
    'accounts_permissions': 'Accounts & Permissions',
    'add_new_user': 'Add New User',
    'loading_accounts': 'Loading Accounts...',
    'created_at_label': 'Created At',
    'no_users_found': 'No users found',
    'new_user_account': 'New User Account',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'password_label': 'Password',
    'role_label': 'Role',
    'standard_user': 'Standard User',
    'system_admin': 'System Administrator',
    'update_account': 'UPDATE ACCOUNT',
    'create_account': 'CREATE ACCOUNT',
    'confirm_delete': 'Confirm Delete',
    'reports': 'Reports',
    'history_archive': 'History & Archive',
    'manage_dashboard': 'Manage Dashboard',
    'export_excel': 'Export Excel',
    'filter_results': 'Filter results...',
    'item_info_th': 'Item Info',
    'timestamp_th': 'Timestamp',
    'diff_th': 'Diff',
    'no_results_found': 'No opname results found.',
    'showing_page': 'Showing page {current} of {total}',
    'yes_clear_all': 'Yes, Clear All',
    'export_error': 'Export Error',
    'clear_history_title': 'Clear All History',
    'clear_history_msg': 'Are you sure you want to permanently delete all stock opname records? This action cannot be reversed.',
    'welcome_back': 'Welcome Back',
    'enter_credentials': 'Enter your credentials to manage your inventory',
    'invalid_login': 'Invalid email or password',
    'unexpected_error': 'An unexpected error occurred',
    'login_to_dashboard': 'Login to Dashboard',
    'session_complete': 'Session Complete'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ID');

  useEffect(() => {
    const saved = localStorage.getItem('app_lang') as Language;
    if (saved && (saved === 'ID' || saved === 'EN')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  const t = (key: string, variables?: Record<string, string | number>): string => {
    let text = translations[language][key as keyof typeof translations['ID']] || key;
    
    if (variables) {
      Object.entries(variables).forEach(([vKey, vValue]) => {
        text = text.replace(`{${vKey}}`, vValue.toString());
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
